<a href="https://colab.research.google.com/github/Rokibul-Islam-Robi/-DS422-Machine-Learning-Driven-Data-Analysis-I-/blob/main/DS422_Lab_Report01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Import numpy as np and print the version number.**

In [1]:
import numpy as np
print(f'Numpy Version: {np.__version__}')

Numpy Version: 2.0.2


# **2. Create a 1D array of numbers from 0 to 9.**

In [2]:
arr_1d = np.arange(10)
print(arr_1d)

[0 1 2 3 4 5 6 7 8 9]


# **3. Create a 3×3 numpy array of all True’s.**

In [3]:
arr_true = np.full((3, 3), True, dtype=bool)
print(arr_true)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# **4. Extract all odd numbers from arr.**

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

odd_nums = arr[arr % 2 == 1]
print(f'Odd Numbers: {odd_nums}')

Odd Numbers: [1 3 5 7 9]


# **5. Replace all odd numbers in arr with -1.**

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# **6. Replace all odd numbers in arr with -1 without changing arr. (where function)**

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_new = np.where(arr % 2 == 1, -1, arr)

print(f'Replaced Array: {arr_new}')
print(f'Original arr: {arr}')

Replaced Array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Original arr: [0 1 2 3 4 5 6 7 8 9]


# **7. Convert a 1D array to a 2D array with 2 rows.**

In [8]:
arr = np.arange(10)

arr_2d = arr.reshape(2, -1)
print(arr_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


# **8. Stack arrays a and b vertically.**

In [9]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(a, "\n")
print(b, "\n")

arr_vertical = np.vstack([a, b])
print(arr_vertical)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[1 1 1 1 1]
 [1 1 1 1 1]] 

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# **9. Stack the arrays a and b horizontally.**

In [10]:
arr_horizontal = np.hstack([a, b])
print(arr_horizontal)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


# **10. Create the following pattern without hardcoding. Use only numpy functions and the below input array a. (np.repeat, np.tile)**

In [11]:
a = np.array([1, 2, 3])
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

part1 = np.repeat(a, 3)
part2 = np.tile(a, 3)
pattern = np.concatenate([part1, part2])
print(pattern)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


# **11. Get the common items between a and b.**

In [13]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

common_items = np.intersect1d(a, b)
print(common_items)

[2 4]


# **12. From array a remove all items present in array b.**

In [14]:
a_minus_b = np.setdiff1d(a, b)

print(a_minus_b)

[1 3 5 6]


# **13. Get the positions where elements of a and b match.**

In [15]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

match_positions_equal = np.where(a == b)[0]
print(match_positions_equal)

[]


# **14. Get all items between 5 and 10 from a.**

In [16]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

filtered_items = a[(a >= 5) & (a <= 10)]
print(filtered_items)

[ 6  9 10]


# **15. Swap columns 1 and 2 in the array arr.**

In [17]:
arr = np.arange(9).reshape(3, 3)
print(arr)

arr_swapped_cols = arr[:, [0, 2, 1]]
print(arr_swapped_cols)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


# **16. Swap rows 1 and 2 in the array arr.**

In [18]:
arr = np.arange(9).reshape(3, 3)
print(arr, "\n")

arr_swapped_rows = arr[[0, 2, 1], :]
print(arr_swapped_rows)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0 1 2]
 [6 7 8]
 [3 4 5]]


# **17. Reverse the rows of a 2D array arr.**

In [19]:
arr = np.arange(9).reshape(3, 3)

arr_reversed_rows = arr[::-1, :]
print(arr_reversed_rows)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


# **18. Reverse the columns of a 2D array arr.**

In [20]:
arr = np.arange(9).reshape(3, 3)

arr_reversed_cols = arr[:, ::-1]
print(arr_reversed_cols)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


# **19. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.**

In [21]:
rand_arr = np.random.random((5, 3)) * 5 + 5

print(rand_arr)

[[9.62438097 9.11696697 7.54677142]
 [9.46985981 5.17594193 7.44763757]
 [7.75068988 7.66919337 9.71539995]
 [8.82679448 5.14582438 8.00837113]
 [9.77450051 6.42696927 8.4510657 ]]


# **20. Print or show only 3 decimal places of the numpy array rand_arr.**

In [22]:
rand_arr = np.random.random((5, 3))

np.set_printoptions(precision=3)
print(rand_arr)

[[0.845 0.403 0.568]
 [0.281 0.649 0.746]
 [0.737 0.382 0.32 ]
 [0.783 0.432 0.599]
 [0.86  0.981 0.523]]


# **21. Pretty print rand_arr by suppressing the scientific notation (like 1e10).**

In [23]:
np.set_printoptions(suppress=True)

print(np.random.random(5) * 1e-6)
np.set_printoptions(suppress=False, precision=8)

[0. 0. 0. 0. 0.]


# **22. Limit the number of items printed in python numpy array a to a maximum of 6 elements.**

In [24]:
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


# **23. Print the full numpy array a without truncating.**

In [25]:
np.set_printoptions(threshold=np.inf)
print(a)

np.set_printoptions(threshold=1000)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# **24. Import the iris dataset keeping the text intact.**

In [26]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]


# **25. Extract the text column species from the 1D iris imported in previous question.**

In [27]:
species = iris[:, 4]
print(species[:5])

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


# **26. Convert the 1D iris to 2D array iris_2d by omitting the species text field.**

In [28]:
iris_2d = iris[:, :4].astype(float)
print(iris_2d[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


# **27. Find the mean, median, standard deviation of iris's sepallength (1st column).**

In [29]:
sepallength = iris_2d[:, 0]
mean_val = np.mean(sepallength)
median_val = np.median(sepallength)
std_val = np.std(sepallength)

print(f"Mean: {mean_val:.2f}, Median: {median_val:.2f}, Std Dev: {std_val:.2f}")

Mean: 5.84, Median: 5.80, Std Dev: 0.83


# **28. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.**

In [30]:
S_min = sepallength.min()
S_max = sepallength.max()
sepallength_normalized = (sepallength - S_min) / (S_max - S_min)

print(sepallength_normalized[:5])

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444]


# **29. Find the 5th and 95th percentile of iris's sepallength.**

In [31]:
perc_5 = np.percentile(sepallength, 5)
perc_95 = np.percentile(sepallength, 95)
print(f"5th: {perc_5:.2f}, 95th: {perc_95:.2f}")

5th: 4.60, 95th: 7.25


# **30. Insert np.nan values at 20 random positions in iris_2d dataset.**

In [32]:
iris_with_nan = iris_2d.copy()
num_nans = 20
rand_rows = np.random.randint(0, iris_with_nan.shape[0], num_nans)
rand_cols = np.random.randint(0, iris_with_nan.shape[1], num_nans)
iris_with_nan[rand_rows, rand_cols] = np.nan

print(f"Total NaNs inserted: {np.isnan(iris_with_nan).sum()}")

Total NaNs inserted: 19


# **31. Find the number and position of missing values in iris_2d's sepallength.**

In [33]:
sepallength_nan = iris_with_nan[:, 0]
nan_count = np.isnan(sepallength_nan).sum()
nan_positions = np.where(np.isnan(sepallength_nan))[0]

print(f"Number of NaNs: {nan_count}")
print(f"Positions of NaNs: {nan_positions}")

Number of NaNs: 5
Positions of NaNs: [ 13  34  50 103 110]


# **32. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0.**

In [34]:
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
filtered_rows = iris_2d[condition]

print("Filtered Rows (P.L > 1.5 & S.L < 5.0)\n")
print(filtered_rows[:5])

Filtered Rows (P.L > 1.5 & S.L < 5.0)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]]


# **33. Select the rows of iris_2d that does not have any nan value.**

In [35]:
rows_without_nan = iris_with_nan[~np.isnan(iris_with_nan).any(axis=1)]

print(f"Original shape: {iris_with_nan.shape}")
print(f"Cleaned shape: {rows_without_nan.shape}")

Original shape: (150, 4)
Cleaned shape: (132, 4)


# **34. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d.**

In [36]:
corr_matrix = np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])
correlation = corr_matrix[0, 1]
print(f"Correlation (SL vs PL): {correlation}")

Correlation (SL vs PL): 0.8717541573048718


# **35. Find out if iris_2d has any missing values.**

In [37]:
has_nan = np.isnan(iris_with_nan).any()

print(f"Does the array have any NaNs? {"Yes" if has_nan else "No"}")

Does the array have any NaNs? Yes


# **36. Replace all ccurrences of nan with 0 in numpy array.**

In [38]:
iris_zeroed = np.nan_to_num(iris_with_nan, nan=0.0)

print(f"NaNs before: {np.isnan(iris_with_nan).sum()}")
print(f"NaNs after: {np.isnan(iris_zeroed).sum()}")

NaNs before: 19
NaNs after: 0


# **37. Find the unique values and the count of unique values in iris's species.**

In [39]:
unique_values, counts = np.unique(species, return_counts=True)

print(dict(zip(unique_values, counts)))

{b'Iris-setosa': np.int64(50), b'Iris-versicolor': np.int64(50), b'Iris-virginica': np.int64(50)}
